[project]
name = "g2p"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rana Gaber", email = "ranagaber046@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "transformers>=5.15.0",
]

[project.scripts]
g2p = "g2p:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
